### ISSUE TITLE
Error: TSAnalysis.get_bounded_log

### ISSUE THREAD

**Issue by ronb1000** [fipelle/TSAnalysis.jl#14]
Trying to run Estimation of state-space models example. Call to res = Optim.optimize(θ_unbound->fmin(θ_unbound, Y, s=12), ... returns with error TSAnalysis.get_bounded_log. Help.

**Comment by fipelle** [comment]
I am aware there are some compatibility issues with the most up-to-date version of Julia. I suppose that you should install the LTS version and pin a few packages to make it work for now. I have been working on a major update for a while, but it is taking a bit longer than expected to release it.
