### ISSUE TITLE
I have ARFIMA, you can use it

### ISSUE THREAD

**Issue by Datseris** [fipelle/TSAnalysis.jl#8]
Just letting you know of this: https://github.com/Datseris/ARFIMA.jl  that you may want to use.

**Comment by fipelle** [comment]
Thank you again. I will take a serious look as soon as I will start implementing simulations. I detailed a plan for the next releases at [this link](https://discourse.julialang.org/t/tsanalysis-time-series-analysis-and-state-space-modelling/). I will look back at your package and try to implement simulations for most models when I will work on v0.1.6. 

At the moment, I am working on implementing VARIMA models (estimation and forecast) - in a similar fashion to what is currently implemented for the ARIMA models.

**Comment by fipelle** [comment]
I will keep this issue opened and look back at it as soon as I get to v0.1.5.

**Comment by fipelle** [comment]
I have decided to close this issue. In the near future, I do not plan to add fractional models.
