### ISSUE TITLE
Auto [V]AR[I]MA[X]

### ISSUE THREAD

**Issue by salma-rodriguez** [fipelle/TSAnalysis.jl#9]
As discussed, the issue is with providing an “auto.arima”-like function, as can be found in R.

**Comment by fipelle** [comment]
Thank you for posting it. I will work on it after the next release.

**Comment by azev77** [comment]
https://github.com/cran/LongMemoryTS/blob/master/R/VARFIMA_est.R

**Comment by fipelle** [comment]
I have started working on the subsampling methods that I want to use for the "auto.arima"-like function (also for VARIMAs). I have included some functions I released under another [unregistered package](https://github.com/fipelle/ElasticNetVAR.jl) for jackknife subsampling. I am working on the stationary Bootstrap and the unit tests.

**Comment by fipelle** [comment]
Just released a new version with these subsampling methods. I have not written the high-level interface to select the hyperparameters for VARIMA models. Theoretically, you could use these new subsampling methods already to structure a grid or a random search. This should be somewhat equivalent to the auto-varima.

Note: The estimation for the VARIMA models is somewhat slow in the presence of many missing observations. Therefore, I think I will implement an EM algorithm as well for estimation purposes. This could be released either as a pre-release prior to the auto-varima, or together.

**Comment by azev77** [comment]
Nice! 
Is it possible to compute conf intervals for the forecasts? 

Also, I'm not sure if this is w/i the scope of your package, but it's often convenient to derive [IRFs w/ confidence bands](http://lenkiefer.com/2020/02/25/housing-response-to-a-consumer-confidence-shock/). 
Luca has some [nice options here](https://github.com/lucabrugnolini/VectorAutoregressions.jl).

**Comment by fipelle** [comment]
I moved this part of the discussion in a different issue.

**Comment by fipelle** [comment]
Implemented in a child package. It will be out by the end of summer. Details will follow.
